export interface BlogPost {
  id: string;
  title: string;
  description: string;
  slug: string;
  liveUrl: string;
  author: { name: string; email: string };
  createdAt: string;
  tags: string[];
}

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'The Complete Vibe Marketing Revolution: AI-Driven Emotional Branding for 2025',
    description: 'Vibe marketing has emerged as the most transformative digital strategy, combining emotional intelligence with AI automation at scale. This guide covers market growth, a 4-week implementation framework, and case studies showing 70–80% cost reductions and dramatically higher engagement.',
    slug: 'the-complete-vibe-marketing-revolution-ai-driven-emotional-branding-for-2025',
    liveUrl: 'https://thedigitaltriangle.com/blog/the-complete-vibe-marketing-revolution-ai-driven-emotional-branding-for-2025/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2025-10-10').toISOString(),
    tags: ['AI Marketing', 'Emotional Branding'],
  },
  {
    id: '2',
    title: 'How Tier-2 D2C Brands Compete with Unicorns Using Kyde Funnels',
    description: "Smaller D2C brands in India can punch above their weight by leveraging WhatsApp automation and conversational commerce through Kyde's platform. This guide covers retention-focused strategies, regional market dynamics, and a case study showing 3.5× repeat order growth.",
    slug: 'how-tier-2-d2c-brands-compete-with-unicorns-using-kyde-funnels',
    liveUrl: 'https://thedigitaltriangle.com/blog/how-tier-2-d2c-brands-compete-with-unicorns-using-kyde-funnels/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2025-10-09').toISOString(),
    tags: ['D2C', 'WhatsApp Commerce'],
  },
  {
    id: '3',
    title: 'The Ultimate Guide To Checking Website Traffic For Businesses',
    description: 'Monitoring site traffic reveals which marketing efforts bring the most visitors, which pages convert best, and where to double down. This guide covers five analytics platforms — Google Analytics, Search Console, SEMrush, Ahrefs, and SimilarWeb — with step-by-step setup instructions.',
    slug: 'the-ultimate-guide-to-checking-website-traffic-for-businesses',
    liveUrl: 'https://thedigitaltriangle.com/blog/the-ultimate-guide-to-checking-website-traffic-for-businesses/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2025-03-18').toISOString(),
    tags: ['SEO', 'Analytics'],
  },
  {
    id: '4',
    title: 'SEO Pricing In India: Affordable Plans That Drive Results',
    description: 'SEO pricing in India ranges from ₹8,000 to ₹1,00,000+ per month depending on scope, competition, and deliverables. This guide breaks down different pricing models, what each tier includes, and how to choose a plan that moves the needle for your business.',
    slug: 'seo-pricing-in-india-affordable-plans-that-drive-results',
    liveUrl: 'https://thedigitaltriangle.com/blog/seo-pricing-in-india-affordable-plans-that-drive-results/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2024-12-27').toISOString(),
    tags: ['SEO', 'India'],
  },
  {
    id: '5',
    title: 'How To Go Viral On Instagram In 2025: Tips & Tricks',
    description: 'Going viral on Instagram in 2025 requires more than luck — it demands a strategy built on audience analysis, high-quality content, and smart hashtag use. This guide covers the exact techniques to create shareable content and maximise your reach on the platform.',
    slug: 'how-to-go-viral-on-instagram-in-2025-tips-tricks',
    liveUrl: 'https://thedigitaltriangle.com/blog/how-to-go-viral-on-instagram-in-2025-tips-tricks/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2024-12-18').toISOString(),
    tags: ['Social Media', 'Instagram'],
  },
  {
    id: '6',
    title: 'Email Copywriting Secrets: How To Write Emails That People Actually Read',
    description: 'Most marketing emails get ignored — the problem is almost always the copy. This guide covers the email copywriting fundamentals that matter: subject lines, personalisation, structure, and CTAs that drive conversions rather than unsubscribes.',
    slug: 'email-copywriting-secrets-how-to-write-emails-that-people-actually-read',
    liveUrl: 'https://thedigitaltriangle.com/blog/email-copywriting-secrets-how-to-write-emails-that-people-actually-read/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2024-12-10').toISOString(),
    tags: ['Email Marketing', 'Copywriting'],
  },
  {
    id: '7',
    title: 'Email Marketing For D2C: Proven Strategies To Drive Sales In 2024',
    description: 'Successful D2C brands use email marketing as a precision instrument — personalised flows, segmented lists, and automated sequences that compound revenue over time. Covers welcome flows, cart recovery, post-purchase, and win-back campaigns purpose-built for direct-to-consumer brands.',
    slug: 'email-marketing-for-d2c-proven-strategies-to-drive-sales-in-2024',
    liveUrl: 'https://thedigitaltriangle.com/blog/email-marketing-for-d2c-proven-strategies-to-drive-sales-in-2024/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2024-11-28').toISOString(),
    tags: ['Email Marketing', 'D2C'],
  },
  {
    id: '8',
    title: '10 Proven Social Media Marketing Strategies for Startups',
    description: 'Social media is the most cost-effective growth channel for startups — but only with the right strategy. This guide covers platform selection, content planning, community building, and paid amplification tactics to drive sustainable audience growth.',
    slug: '10-proven-social-media-marketing-strategies-for-startups',
    liveUrl: 'https://thedigitaltriangle.com/blog/10-proven-social-media-marketing-strategies-for-startups/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2024-11-22').toISOString(),
    tags: ['Social Media', 'Startup'],
  },
  {
    id: '9',
    title: 'PPC Advertising For Small Business: How To Maximize ROI And Drive Growth In 2024',
    description: 'PPC advertising lets small businesses appear alongside industry giants — but the margin for error is thin. This guide covers campaign setup, audience targeting, budget optimisation, and measurement frameworks to maximise ROAS across Google Ads and Meta.',
    slug: 'ppc-advertising-for-small-business-how-to-maximize-roi-and-drive-growth-in-2024',
    liveUrl: 'https://thedigitaltriangle.com/blog/ppc-advertising-for-small-business-how-to-maximize-roi-and-drive-growth-in-2024/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2024-11-14').toISOString(),
    tags: ['PPC', 'Google Ads'],
  },
  {
    id: '10',
    title: 'Maximizing Bookings: The Ultimate Guide to SEO for Hotels',
    description: "80% of travellers begin their accommodation search online — and most never go past the first page. This complete hotel SEO playbook covers keyword research, local SEO, on-page optimisation, mobile design, and tracking to capture direct bookings.",
    slug: 'maximizing-bookings-the-ultimate-guide-to-seo-for-hotels',
    liveUrl: 'https://thedigitaltriangle.com/blog/maximizing-bookings-the-ultimate-guide-to-seo-for-hotels/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2024-11-08').toISOString(),
    tags: ['SEO', 'Hospitality'],
  },
  {
    id: '11',
    title: 'The Ultimate Guide to Building and Scaling D2C Brand',
    description: 'Direct-to-Consumer marketing eliminates intermediaries and lets brands own the customer relationship end-to-end. This guide covers everything from defining your target audience to building a scalable social media and performance marketing strategy.',
    slug: 'the-ultimate-guide-to-build-d2c-brand',
    liveUrl: 'https://thedigitaltriangle.com/blog/the-ultimate-guide-to-build-d2c-brand/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2023-04-07').toISOString(),
    tags: ['D2C', 'Brand Building'],
  },
  {
    id: '12',
    title: 'Top 10 WhatsApp Business API Providers in India',
    description: "WhatsApp Business API enables businesses to send unlimited messages, automate flows, and integrate with CRMs at scale. This ranked guide covers India's top 10 providers — Interakt, WATI, Twilio, and more — with features, pricing, and best-fit use cases.",
    slug: 'top-10-whatsapp-business-api-in-india',
    liveUrl: 'https://thedigitaltriangle.com/blog/top-10-whatsapp-business-api-in-india/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2022-10-27').toISOString(),
    tags: ['WhatsApp', 'Automation'],
  },
  {
    id: '13',
    title: 'Power Your D2C Brand Marketing with Free Google Tools',
    description: "Before spending on expensive marketing tools, Google's free suite can dramatically improve your D2C brand's visibility, traffic analysis, and campaign performance. This guide walks through the essential tools and how to use them effectively.",
    slug: 'd2c-brand-marketing-with-free-google-tools',
    liveUrl: 'https://thedigitaltriangle.com/blog/d2c-brand-marketing-with-free-google-tools/',
    author: { name: 'Deepika Aggarwal', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2022-09-03').toISOString(),
    tags: ['D2C', 'Google Tools'],
  },
  {
    id: '14',
    title: 'Top 30 Email Campaign Templates for D2C Brands',
    description: 'Great D2C email marketing starts with proven frameworks, not blank pages. This guide covers 30 ready-to-use templates from successful brands spanning promotional, engagement, welcome, and newsletter campaigns.',
    slug: 'top-30-email-campaigns-for-d2c-brands',
    liveUrl: 'https://thedigitaltriangle.com/blog/top-30-email-campaigns-for-d2c-brands/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2022-08-02').toISOString(),
    tags: ['Email Marketing', 'Templates'],
  },
  {
    id: '15',
    title: 'A Definitive Guide On WhatsApp Commerce',
    description: "WhatsApp's 2 billion users make it the world's largest untapped commerce channel. This guide shows businesses how to leverage automation, product catalogues, and WhatsApp Business API to build a commerce pipeline that converts.",
    slug: 'a-definitive-guide-on-whatsapp-commerce',
    liveUrl: 'https://thedigitaltriangle.com/blog/a-definitive-guide-on-whatsapp-commerce/',
    author: { name: 'Deepika Aggarwal', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2022-06-02').toISOString(),
    tags: ['WhatsApp', 'Commerce'],
  },
  {
    id: '16',
    title: 'Top 20 Buy Now Pay Later (BNPL) Companies In India',
    description: "India's BNPL market — currently at $3–3.5 billion — is projected to reach $45–50 billion by 2026, driven by post-pandemic digital adoption and rising demand for flexible payments. This guide covers the top 20 BNPL providers and which e-commerce brands should use them.",
    slug: 'buy-now-pay-later-companies-in-india',
    liveUrl: 'https://thedigitaltriangle.com/blog/buy-now-pay-later-companies-in-india/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2022-05-26').toISOString(),
    tags: ['Fintech', 'E-commerce'],
  },
  {
    id: '17',
    title: 'How Traditional Business Can Transform Into D2C Business',
    description: 'Every traditional business — retail, wholesale, or manufacturing — can transition to a Direct-to-Consumer model by rethinking customer relationships, supply chain, and marketing. This guide provides a practical roadmap for the mindset and operational shifts required.',
    slug: 'how-to-transform-into-d2c-business',
    liveUrl: 'https://thedigitaltriangle.com/blog/how-to-transform-into-d2c-business/',
    author: { name: 'Deepika Aggarwal', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2022-05-18').toISOString(),
    tags: ['D2C', 'Strategy'],
  },
  {
    id: '18',
    title: 'Top 40 D2C Brands to Watch Out in 2025',
    description: 'From health and wellness to fashion and home goods, these 40 D2C brands are setting the pace in India and globally — with innovation, community-first marketing, and smart digital strategies. A must-read for brand builders and investors alike.',
    slug: 'top-40-d2c-brands-to-watch-out-in-2025',
    liveUrl: 'https://thedigitaltriangle.com/blog/top-40-d2c-brands-to-watch-out-in-2025/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2022-04-24').toISOString(),
    tags: ['D2C', 'Brands'],
  },
  {
    id: '19',
    title: 'Top 30 Coupon Sites for E-commerce Stores in India',
    description: "Listing your products on coupon aggregator sites can drive significant incremental revenue with minimal effort. This guide covers India's top 30 coupon and deals platforms, how they work, and which categories benefit most.",
    slug: 'top-30-coupon-sites-for-e-commerce-stores',
    liveUrl: 'https://thedigitaltriangle.com/blog/top-30-coupon-sites-for-e-commerce-stores/',
    author: { name: 'Deepika Aggarwal', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2022-02-03').toISOString(),
    tags: ['E-commerce', 'Coupons'],
  },
  {
    id: '20',
    title: 'Deciphering the D2C Brands Jargon',
    description: 'CAC, LTV, AOV, ROAS, MER — the D2C world runs on acronyms that can overwhelm newcomers. This guide demystifies D2C terminology and explains how the model differs from B2B, B2C, and private label businesses.',
    slug: 'deciphering-d2c-brands-jargon',
    liveUrl: 'https://thedigitaltriangle.com/blog/deciphering-d2c-brands-jargon/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2021-09-09').toISOString(),
    tags: ['D2C', 'Education'],
  },
  {
    id: '21',
    title: 'Top 50 Excel Formulas Every E-commerce Owner Should Know',
    description: 'Excel formulas turn basic spreadsheets into powerful business intelligence tools — from SUM and VLOOKUP to advanced FILTER and array functions. Covers the 50 essential formulas every e-commerce operator needs for faster, smarter decisions.',
    slug: 'top-50-excel-formulas-every-e-commerce-owner-should-know',
    liveUrl: 'https://thedigitaltriangle.com/blog/top-50-excel-formulas-every-e-commerce-owner-should-know/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2021-04-16').toISOString(),
    tags: ['E-commerce', 'Tools'],
  },
  {
    id: '22',
    title: '21 Top Content Ideas For Your E-Commerce Store',
    description: 'Quality content helps e-commerce stores outrank competitors, build trust, and convert browsers into buyers. This guide covers 21 actionable content ideas — from product videos and customer stories to seasonal campaigns and comparison guides.',
    slug: 'top-content-ideas-for-your-ecommerce-store',
    liveUrl: 'https://thedigitaltriangle.com/blog/top-content-ideas-for-your-ecommerce-store/',
    author: { name: 'Harsh', email: 'info@digitaltriangle.in' },
    createdAt: new Date('2021-04-16').toISOString(),
    tags: ['E-commerce', 'Content'],
  },
];

export const POST_BY_SLUG: Record<string, BlogPost> = Object.fromEntries(
  BLOG_POSTS.map(p => [p.slug, p])
);
