import { Metadata } from 'next';
import Link from 'next/link';
import { Reveal } from '@/components/ui/Reveal';
import { Footer } from '@/components/Footer';
import { buildPageMetadata } from '@/lib/seo';

export const revalidate = 300;

export async function generateMetadata(): Promise<Metadata> {
  return buildPageMetadata('/solutions/ai-automation', {
    title: 'AI & Marketing Automation Systems',
    description: 'We wire Claude, GPT, and Gemini into your marketing operations — research, creative briefing, campaign monitoring, and CRM flows. All automated.',
  });
}

const SYSTEMS = [
  {
    icon: '⚡',
    title: 'AI Research Intelligence',
    desc: 'Real-time competitor monitoring, trend detection, and market intelligence — all synthesized into weekly briefings by AI. No manual research hours.',
    tags: ['Competitor Tracking', 'Trend Detection', 'Market Intelligence', 'Auto-Reports'],
    color: '#4b6bff',
  },
  {
    icon: '✦',
    title: 'AI Content Briefing System',
    desc: 'From keyword to detailed content brief in minutes. Our AI system handles SEO intent mapping, outline creation, competitor analysis, and internal linking suggestions.',
    tags: ['Brief Generation', 'Intent Mapping', 'SEO Integration', 'Competitor Analysis'],
    color: '#8b5cf6',
  },
  {
    icon: '◉',
    title: 'Campaign Monitoring & Alerts',
    desc: 'AI-powered anomaly detection across all paid channels. Get alerted when CPC spikes, ROAS drops, or creative fatigue sets in — before it costs you.',
    tags: ['Anomaly Detection', 'Real-Time Alerts', 'Performance Monitoring', 'Budget Controls'],
    color: '#10b981',
  },
  {
    icon: '◎',
    title: 'WhatsApp & Chat Automation',
    desc: 'AI-powered WhatsApp chatbots for lead qualification, order updates, cart recovery, and customer support. Built on the official Business API.',
    tags: ['WhatsApp API', 'Lead Qualification', 'Cart Recovery', 'Order Updates'],
    color: '#c026d3',
  },
  {
    icon: '≋',
    title: 'Martech Stack Integration',
    desc: 'We connect your CRM, ESP, ad platforms, analytics tools, and data warehouse into one unified intelligence layer. No more siloed data.',
    tags: ['CRM Integration', 'Data Unification', 'Platform Connectors', 'Webhook Automation'],
    color: '#f59e0b',
  },
  {
    icon: '⊕',
    title: 'Custom AI Model Fine-Tuning',
    desc: 'Train a version of Claude or GPT-4 on your brand\'s tone, product knowledge, and customer language. Brand-consistent AI that knows your business.',
    tags: ['Model Fine-Tuning', 'Brand Voice AI', 'Product Knowledge Base', 'Custom LLMs'],
    color: '#e11d8a',
  },
];

const AUTOMATION_FLOWS = [
  { title: 'Lead → Nurture → Close', desc: 'New lead captured → Instant WhatsApp/SMS follow-up → Segmented email nurture → Sales CRM update → Reminder triggers. Zero manual intervention.' },
  { title: 'Ad Alert → Creative Swap', desc: 'ROAS drops below threshold → Slack alert to team → Auto-pause underperformer → Creative variant queued → Campaign resumed with fresh creative.' },
  { title: 'Content → Publish → Report', desc: 'Brief generated by AI → Human review → Auto-publish at optimal time → Performance data fed back to AI for next brief optimization.' },
  { title: 'Order → Retention → LTV', desc: 'Post-purchase email triggered → Day 7 review request → Day 30 upsell recommendation → Day 90 win-back flow. Fully automated lifecycle.' },
];

const RESULTS = [
  { value: '120hr', label: 'Saved per brand per month', brand: 'Avg across portfolio' },
  { value: '4×', label: 'Content production speed', brand: 'AI-assisted workflow' },
  { value: '38%', label: 'Repeat purchase rate lift', brand: 'WhatsApp automation' },
  { value: '72hr', label: 'First automation live', brand: 'Onboarding SLA' },
];

export default function AIAutomationPage() {
  return (
    <>
      <div style={{ minHeight: '100vh', backgroundColor: 'var(--bg-0)', paddingTop: '64px' }}>

        <section className="page-hero" style={{ padding: 'clamp(72px, 11vw, 120px) 0 clamp(48px, 7vw, 80px)', borderBottom: '1px solid var(--line)' }}>
          <div className="hero-orb-l" style={{ background: 'radial-gradient(circle, rgba(75,107,255,0.2), transparent 65%)' }} />
          <div className="hero-orb-r" style={{ background: 'radial-gradient(circle, rgba(139,92,246,0.14), transparent 65%)' }} />
          <div className="grid-bg" />
          <div className="shell" style={{ position: 'relative', zIndex: 1 }}>
            <Reveal direction="up" delay={0.04}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '20px' }}>
                <span className="section-tag" style={{ color: 'var(--brand-blue)' }}>⚡ AI & Automation</span>
              </div>
            </Reveal>
            <Reveal direction="up" delay={0.08}>
              <h1 style={{ fontSize: 'clamp(2.8rem, 6vw, 5rem)', fontWeight: 800, lineHeight: 1.0, letterSpacing: '-0.035em', color: 'var(--fg-0)', marginBottom: '24px', maxWidth: '780px' }}>
                AI systems that run<br />
                <span className="grad-text">
                  your marketing 24/7.
                </span>
              </h1>
            </Reveal>
            <Reveal direction="up" delay={0.12}>
              <p style={{ fontSize: 'clamp(1rem, 2vw, 1.2rem)', lineHeight: 1.7, color: 'var(--fg-1)', maxWidth: '620px', marginBottom: '36px' }}>
                We wire Claude, GPT, Gemini, and open-source models into your marketing operations — research, briefing, campaign monitoring, CRM flows, and customer communication. The machine runs while you focus on the business.
              </p>
            </Reveal>
            <Reveal direction="up" delay={0.16}>
              <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
                <Link href="/contact" style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '13px 26px', borderRadius: '999px', background: 'linear-gradient(135deg, #4b6bff, #8b5cf6)', color: 'white', fontWeight: '700', fontSize: '0.95rem', textDecoration: 'none' }}>
                  Automate My Marketing →
                </Link>
                <Link href="/case-studies" style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '13px 26px', borderRadius: '999px', border: '1px solid var(--line-strong)', color: 'var(--fg-1)', fontWeight: '500', fontSize: '0.95rem', textDecoration: 'none' }}>
                  See What We've Built
                </Link>
              </div>
            </Reveal>
          </div>
        </section>

        <section style={{ borderBottom: '1px solid var(--line)', backgroundColor: 'var(--bg-1)' }}>
          <div className="shell">
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '1px', backgroundColor: 'var(--line)' }} className="results-grid">
              {RESULTS.map((r, i) => (
                <Reveal key={r.label} direction="up" delay={0.05 * i}>
                  <div style={{ backgroundColor: 'var(--bg-1)', padding: '28px 20px', textAlign: 'center' }}>
                    <p style={{ fontSize: 'clamp(1.8rem, 3vw, 2.8rem)', fontWeight: 800, letterSpacing: '-0.04em', lineHeight: 1, backgroundImage: 'linear-gradient(135deg, #4b6bff, #8b5cf6)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>{r.value}</p>
                    <p style={{ fontSize: '0.8rem', color: 'var(--fg-2)', margin: '4px 0 2px' }}>{r.label}</p>
                    <p style={{ fontSize: '0.7rem', color: 'var(--fg-3)', fontFamily: 'var(--font-mono)' }}>{r.brand}</p>
                  </div>
                </Reveal>
              ))}
            </div>
          </div>
        </section>

        <section style={{ padding: 'clamp(64px, 9vw, 100px) 0', borderBottom: '1px solid var(--line)' }}>
          <div className="shell">
            <div style={{ marginBottom: '52px' }}>
              <Reveal direction="up">
                <p style={{ fontSize: '0.68rem', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.12em', color: 'var(--brand-blue)', marginBottom: '12px' }}>AI SYSTEMS WE BUILD</p>
                <h2 style={{ fontSize: 'clamp(2rem, 4vw, 3rem)', fontWeight: 700, lineHeight: 1.1, letterSpacing: '-0.03em', color: 'var(--fg-0)' }}>
                  Six AI systems,<br />
                  <span style={{ color: 'var(--fg-2)' }}>one marketing OS.</span>
                </h2>
              </Reveal>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '16px' }} className="systems-grid">
              {SYSTEMS.map((s, i) => (
                <Reveal key={s.title} direction="up" delay={0.06 * i}>
                  <div style={{ backgroundColor: 'var(--bg-1)', border: '1px solid var(--line)', borderRadius: '16px', padding: '28px', height: '100%' }}>
                    <div style={{ fontSize: '1.5rem', marginBottom: '14px' }}>{s.icon}</div>
                    <h3 style={{ fontSize: '1.05rem', fontWeight: '700', color: 'var(--fg-0)', marginBottom: '10px' }}>{s.title}</h3>
                    <p style={{ fontSize: '0.875rem', lineHeight: 1.65, color: 'var(--fg-2)', marginBottom: '16px' }}>{s.desc}</p>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
                      {s.tags.map(t => (
                        <span key={t} style={{ padding: '3px 10px', borderRadius: '999px', backgroundColor: s.color + '15', border: `1px solid ${s.color}30`, fontSize: '0.72rem', color: s.color, fontWeight: '500' }}>{t}</span>
                      ))}
                    </div>
                  </div>
                </Reveal>
              ))}
            </div>
          </div>
        </section>

        {/* Automation Flows */}
        <section style={{ padding: 'clamp(64px, 9vw, 100px) 0', borderBottom: '1px solid var(--line)', backgroundColor: 'var(--bg-1)' }}>
          <div className="shell">
            <div style={{ marginBottom: '52px' }}>
              <Reveal direction="up">
                <p style={{ fontSize: '0.68rem', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.12em', color: 'var(--brand-blue)', marginBottom: '12px' }}>EXAMPLE AUTOMATIONS</p>
                <h2 style={{ fontSize: 'clamp(2rem, 4vw, 3rem)', fontWeight: 700, lineHeight: 1.1, letterSpacing: '-0.03em', color: 'var(--fg-0)' }}>
                  Flows that run<br />
                  <span style={{ color: 'var(--fg-2)' }}>while you sleep.</span>
                </h2>
              </Reveal>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '16px' }} className="flows-grid">
              {AUTOMATION_FLOWS.map((f, i) => (
                <Reveal key={f.title} direction="up" delay={0.07 * i}>
                  <div style={{ backgroundColor: 'var(--bg-2)', border: '1px solid rgba(99,102,241,0.2)', borderRadius: '16px', padding: '28px' }}>
                    <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '4px 12px', borderRadius: '999px', backgroundColor: 'rgba(75,107,255,0.1)', marginBottom: '14px' }}>
                      <span style={{ width: '6px', height: '6px', borderRadius: '50%', backgroundColor: 'var(--brand-blue)', flexShrink: 0 }} />
                      <span style={{ fontSize: '0.72rem', fontWeight: '700', color: 'var(--brand-blue)', fontFamily: 'var(--font-mono)' }}>{f.title}</span>
                    </div>
                    <p style={{ fontSize: '0.9rem', lineHeight: 1.7, color: 'var(--fg-2)' }}>{f.desc}</p>
                  </div>
                </Reveal>
              ))}
            </div>
          </div>
        </section>

        <section style={{ padding: 'clamp(72px, 10vw, 112px) 0', textAlign: 'center', background: 'radial-gradient(ellipse 80% 50% at 50% 100%, rgba(99,102,241,0.1), transparent)' }}>
          <div className="shell">
            <Reveal direction="up">
              <h2 style={{ fontSize: 'clamp(2rem, 4.5vw, 3.5rem)', fontWeight: 800, lineHeight: 1.05, letterSpacing: '-0.03em', color: 'var(--fg-0)', marginBottom: '16px' }}>
                Ready to automate your<br />entire marketing stack?
              </h2>
              <p style={{ fontSize: '1.05rem', color: 'var(--fg-1)', marginBottom: '36px', maxWidth: '440px', margin: '0 auto 36px' }}>
                We'll map your current marketing ops, identify the 3 highest-leverage automations, and show you what an AI-native marketing stack looks like for your business.
              </p>
              <div style={{ display: 'flex', gap: '12px', justifyContent: 'center', flexWrap: 'wrap' }}>
                <Link href="/contact" style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '15px 32px', borderRadius: '999px', background: 'linear-gradient(135deg, #4b6bff, #8b5cf6)', color: 'white', fontWeight: '700', fontSize: '1rem', textDecoration: 'none' }}>
                  Get AI Readiness Audit →
                </Link>
                <Link href="/solutions" style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '15px 32px', borderRadius: '999px', border: '1px solid var(--line-strong)', color: 'var(--fg-1)', fontWeight: '500', fontSize: '1rem', textDecoration: 'none' }}>
                  All Solutions
                </Link>
              </div>
            </Reveal>
          </div>
        </section>

      </div>
      <Footer />
      <style>{`
        @media (max-width: 900px) {
          .systems-grid, .flows-grid { grid-template-columns: repeat(2, 1fr) !important; }
          .results-grid { grid-template-columns: repeat(2, 1fr) !important; }
        }
        @media (max-width: 560px) {
          .systems-grid, .flows-grid, .results-grid { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </>
  );
}
